### ISSUE TITLE
Acs events not searching properly

### ISSUE THREAD

**Issue by elodimuore** [elodimuore/eventhub#2]
I've updated the views to conform to MVC pattern, I had to clean the repo due to a merge conflict I couldn't recover from. Now I'm having an issue in home.js,  calling Cloud.search with the longitude, latitude, and distance is supposed to return events associated with a place close the longitude, latitude specified in the search params, but it doesn't return anything.
When I remove the distance field, it returns the first object it finds and nothing else. Please take a look at my code.

**Comment by aaronksaunders** [comment]
what is the specific line number and file... please make it easy to help you.

**Comment by elodimuore** [comment]
https://github.com/elodimuore/eventhub/blob/master/app/controllers/home.js#L14-L33

**Comment by aaronksaunders** [comment]
the answer is in the book, that was required for the class
